server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://root:root@localhost:27017/MEVOCAB?authSource=admin}

app:
  time:
    expiryTime: 3600

key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}

